// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Validate at boot — fail fast with a clear message rather than passing
// `undefined` to createClient and hitting cryptic runtime errors later.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [
    !SUPABASE_URL && "VITE_SUPABASE_URL",
    !SUPABASE_PUBLISHABLE_KEY && "VITE_SUPABASE_PUBLISHABLE_KEY",
  ]
    .filter(Boolean)
    .join(", ");
  throw new Error(
    `[supabase] Missing required environment variables: ${missing}. ` +
      `Copy .env.example to .env and fill in the values.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// sessionStorage keeps the JWT only for the lifetime of the browser tab.
// This limits the XSS token-theft window compared to localStorage (which
// persists indefinitely across tabs and restarts).
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
